@url = http://localhost:3000/generos

GET {{url}}
###
GET {{url}}/2
###
POST {{url}}
Content-Type: application/json

{
    "nome": "ação"
}
###
PUT {{url}}/1
Content-Type: application/json

{
    "nome": "aventura"
}
###
DELETE {{url}}/1
Content-Type: application/json